# Generated by Django 2.2 on 2019-04-11 01:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kr_word', models.CharField(max_length=100, unique=True)),
                ('en_word', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Variable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('snake', models.CharField(default='', max_length=200)),
                ('pascal', models.CharField(default='', max_length=200)),
                ('camel', models.CharField(default='', max_length=200)),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Word')),
            ],
        ),
    ]
