# Generated by Django 2.2 on 2019-04-10 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20190410_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='case',
            name='type',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='variable',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='word',
            name='en_word',
            field=models.CharField(max_length=200),
        ),
    ]
