# Generated by Django 2.2 on 2019-04-12 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_variable_hits'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='variable',
            options={'ordering': ['-hits']},
        ),
    ]
