# Generated by Django 2.2 on 2019-04-10 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20190410_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='en_word',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
