# Generated by Django 2.2 on 2019-04-17 06:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0003_auto_20190412_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='variable',
            name='hit_users',
            field=models.ManyToManyField(related_name='copy_vars', to=settings.AUTH_USER_MODEL),
        ),
    ]
