# Generated by Django 2.2.2 on 2019-10-15 16:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kr_word', models.CharField(max_length=100, unique=True)),
                ('en_word', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Variable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('snake', models.CharField(default='', max_length=200)),
                ('pascal', models.CharField(default='', max_length=200)),
                ('camel', models.CharField(default='', max_length=200)),
                ('hits', models.IntegerField(default=0)),
                ('hit_users', models.ManyToManyField(related_name='copy_vars', to=settings.AUTH_USER_MODEL)),
                ('words', models.ManyToManyField(related_name='variables', to='store.Word')),
            ],
            options={
                'ordering': ['-hits'],
            },
        ),
    ]
