# Generated by Django 2.2 on 2019-04-10 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('wrong', models.CharField(default=None, max_length=50)),
                ('short', models.CharField(default=None, max_length=50)),
                ('slice', models.CharField(default=None, max_length=50)),
                ('sound', models.CharField(default=None, max_length=50)),
            ],
        ),
    ]
